"""Recreate lost migration

Revision ID: b9a8f723cdf1
Revises:
Create Date: 2025-09-17 11:46:49.945734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9a8f723cdf1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects.postgresql import ENUM

# Define the ENUM type
userrole_enum = ENUM("user", "moderator", "admin", name="userrole")


def upgrade():
    # Create the ENUM type in the database
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Add the column using the ENUM type
    op.add_column(
        "users", sa.Column("role", userrole_enum, nullable=False, server_default="user")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
